[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
match_solana_contract = "AovyJcj7yeBXRqDcGtCZKeKv7NP5JVjtpgW8U7jcYdfk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/dave/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
